### ISSUE TITLE
inMemoryDB Application logic

### ISSUE THREAD

**Issue by kvamsij** [kvamsij/IDML-Export#33]
- [x] #34
- [x] #37
- [x] #39
- [x] #41
- [x] #43
- [x] Update dataProcessClient to take process data as an input to method #43 
- [x] #45
- [x] #47
- [x] #50

**DataStore**

- [x] #49
- [x] application logic for Resources data store #49 
- [x] application logic for spreads data store #49 

**IDML Folder System**
- [x] #53
- [x] #55
- [x] #57
